name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd android-refimpl-app ; ./gradlew build

    - name: upload lint
      uses: actions/upload-artifact@v1
      with:
        name: lint report
        path: /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/native-audio-jni/build/reports/lint-results.html



