name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Build with Gradle
      run: cd android-refimpl-app ; ./gradlew assembleRelease

    - name: upload apk
      uses: actions/upload-artifact@v1
      with:
        name: trifa
        path: /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/build/outputs/apk/debug/app-debug.apk

  android-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: android test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd android-refimpl-app ; ./gradlew connectedAndroidTest
